### ISSUE TITLE
我不能处理这个问题，即使我更改的报错的文件

### ISSUE THREAD

**Issue by zcbxxx1** [loseprivacy/loseprivacy-cli#1]
报错如下（在3.9与3.10中皆是如此）
08/04/2022 08:23:27 AM 首次运行，将从LosePrivacy服务器中拉取最新的数据泄露事件的元数据
Traceback (most recent call last):
File "/media/root/onedrive/loseprivacy-cli-master/example.py", line 28, in <module>
main()
File "/media/root/onedrive/loseprivacy-cli-master/example.py", line 22, in main
lp.init_data()
File "/media/root/onedrive/loseprivacy-cli-master/loseprivacy.py", line 65, in init_data
self.dataclasses = self.get_dataclasses()
File "/media/root/onedrive/loseprivacy-cli-master/loseprivacy.py", line 105, in get_dataclasses
rsp = requests.post(url = self.host+self.url_dc, data = {},headers = self.header(), timeout=self.timeout)
File "/usr/lib/python3/dist-packages/requests/api.py", line 117, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
resp = conn.urlopen(
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
httplib_response = self._make_request(
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 239, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/lib/python3.9/http/client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.9/http/client.py", line 1326, in _send_request
self.putheader(hdr, value)
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 224, in putheader
_HTTPConnection.putheader(self, header, *values)
File "/usr/lib/python3.9/http/client.py", line 1258, in putheader
values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)
当我尝试修改/usr/lib/python3.9/http/client.py", line 1258为values[i] = one_value.encode('utf-8')时，再次运行；报错减少了

变为
08/04/2022 08:20:46 AM 首次运行，将从LosePrivacy服务器中拉取最新的数据泄露事件的元数据
Traceback (most recent call last):
File "/media/root/onedrive/loseprivacy-cli-master/example.py", line 28, in <module>
main()
File "/media/root/onedrive/loseprivacy-cli-master/example.py", line 22, in main
lp.init_data()
File "/media/root/onedrive/loseprivacy-cli-master/loseprivacy.py", line 67, in init_data
for dataclass in self.dataclasses:
TypeError: 'NoneType' object is not iterable
我意识到有些什么不对，恢复了文件并退出

**Comment by loseprivacy** [comment]
这看起来是python requests库的问题。可以参考一下requests库的issue：https://github.com/psf/requests/issues/1822

**Comment by loseprivacy** [comment]
这是因为你的api key没有填入，默认的APIkey是一串包含中文的字符串："填入从LosePrivacy获取的API KEY"，需要改为你的API KEY。

你的第二个错误是：没有从服务器返回正确的值，也是因为没有有效的API KEY。

我们会增加库的错误提示。
